.PHONY: clean All

All:
	@echo "----------Building project:[ PECLQuispeAntezanaRodrigoMauricio - Debug ]----------"
	@cd "PECLQuispeAntezanaRodrigoMauricio" && "$(MAKE)" -f  "PECLQuispeAntezanaRodrigoMauricio.mk"
clean:
	@echo "----------Cleaning project:[ PECLQuispeAntezanaRodrigoMauricio - Debug ]----------"
	@cd "PECLQuispeAntezanaRodrigoMauricio" && "$(MAKE)" -f  "PECLQuispeAntezanaRodrigoMauricio.mk" clean
